### ISSUE TITLE
About LR-ASPP module

### ISSUE THREAD

**Issue by zzllc3** [Tramac/mobilenetv3-segmentation#1]
Hi,Tramac,thanks for your work.
I noticed that you use 1*1 conv to make channel = class_num first, and then bilinear upsample in LR-ASPP module. In paper, bilinear upsample is utilized first. What is the difference between these？

**Comment by Tramac** [comment]
Hi, thank you for your careful attention.
It is different from paper, I used a more general method (upsample finally) in semantic segmentation, maybe this will effect performance.
